// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

func InitializeEvent(phrase string) Event {
	message := NewMessage(phrase)
	greeter := NewGreeter(message)
	event := NewEvent(greeter)
	return event
}

func ResponseEvent(phrase string) Response {
	pointer := NewPointer(phrase)
	writer := NewWriter(pointer)
	response := NewResponse(writer)
	return response
}
